export const USER_REGISTER_BEGIN = 'USER_REGISTER_BEGIN'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'

export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const FORGETPASSWORD_BEGIN = 'FORGETPASSWORD_BEGIN'
export const FORGETPASSWORD_SUCCESS = 'FORGETPASSWORD_SUCCESS'
export const FORGETPASSWORD_FAILURE = 'FORGETPASSWORD_FAILURE'

export const RESETPASSWORD_BEGIN = 'RESETPASSWORD_BEGIN'
export const RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS'
export const RESETPASSWORD_FAILURE = 'RESETPASSWORD_FAILURE'

export const EDITPROFILE = 'EDITPROFILE'
export const VIEWPROFILE = 'VIEWPROFILE'

export const THOUGHTADDEDIT_BEGIN = 'THOUGHTADDEDIT_START'
export const THOUGHTADDEDIT_SUCCESS = 'THOUGHTADDEDIT_SUCCESS'
export const THOUGHTADDEDIT_FAILURE = 'THOUGHTADDEDIT_FAILURE'

export const THOUGHTLIST_BEGIN = 'STARTTHOUGHTLIST'
export const THOUGHTSLIST_SUCCESS = 'THOUGHTSLISTSUCCESS'
export const THOUGHTLIST_FAILURE = 'THOUGHTLIST_FAILURE'

export const THOUGHTDELETE_BEGIN = 'STARTTHOUGHTDELETE'
export const THOUGHTSDELETE_SUCCESS = 'THOUGHTSDELETESUCCESS'
export const THOUGHTDELETE_FAILURE = 'THOUGHTDELETE_FAILURE'

export const THOUGHTVIEW_BEGIN = 'THOUGHTVIEW_BEGIN'
export const THOUGHTSVIEW_SUCCESS = 'THOUGHTSVIEW_SUCCESS'
export const THOUGHTVIEW_FAILURE = 'THOUGHTVIEW_FAILURE'

export const DASHBOARDSTATUS_BEGIN = 'DASHBOARDSTATUS_BEGIN'
export const DASHBOARDSTATUS_SUCCESS = 'DASHBOARDSTATUS_SUCCESS'
export const DASHBOARDSTATUS_FAILURE = 'DASHBOARDSTATUS_FAILURE'

export const ACTIONITEM_BEGIN = 'ACTIONITEM_BEGIN'
export const ACTIONITEM_SUCCESS = 'ACTIONITEM_SUCCESS'
export const ACTIONITEM_FAILURE = 'ACTIONITEM_FAILURE'

export const ACTIONITEMLISTING_BEGIN = 'ACTIONITEMLISTING_BEGIN'
export const ACTIONITEMLISTING_SUCCESS = 'ACTIONITEMLISTING_SUCCESS'
export const ACTIONITEMLISTING_FAILURE = 'ACTIONITEMLISTING_FAILURE'

export const ACTIONITEMVIEW_BEGIN = 'ACTIONITEMVIEW_BEGIN'
export const ACTIONITEMVIEW_SUCCESS = 'ACTIONITEMVIEW_SUCCESS'
export const ACTIONITEMVIEW_FAILURE = 'ACTIONITEMVIEW_FAILURE'

export const ACTIONITEMDELETE_BEGIN = 'ACTIONITEMDELETE_BEGIN'
export const ACTIONITEMDELETE_SUCCESS = 'ACTIONITEMDELETE_SUCCESS'
export const ACTIONITEMDELETE_FAILURE = 'ACTIONITEMDELETE_FAILURE'

export const QUESTIONANSWERLISTING_BEGIN = 'QUESTIONANSWERLISTING_BEGIN'
export const QUESTIONANSWERLISTING_SUCCESS = 'QUESTIONANSWERLISTING_SUCCESS'
export const QUESTIONANSWERLISTING_FAILURE = 'QUESTIONANSWERLISTING_FAILURE'

// Fact action////
export const FACT_BEGIN = 'FACT_BEGIN'
export const FACT_SUCCESS = 'FACT_SUCCESS'
export const FACT_FAILURE = 'FACT_FAILURE'

export const FACTLISTING_BEGIN = 'FACTLISTING_BEGIN'
export const FACTLISTING_SUCCESS = 'FACTLISTING_SUCCESS'
export const FACTLISTING_FAILURE = "FACTLISTING_FAILURE"

export const FACTVIEW_BEGIN = "FACTVIEW_BEGIN"
export const FACTVIEW_SUCCESS = 'FACTVIEW_SUCCESS'
export const FACTVIEW_FAILURE = 'FACTVIEW_FAILURE'

export const FACTDELETE_BEGIN = 'FACTDELETE_BEGIN'
export const FACTDELETE_SUCCESS = 'FACTDELETE_SUCCESS'
export const FACTDELETE_FAILURE = 'FACTDELETE_FAILURE'
 
//end fact acrtion ///




// export const QUESTIONANSWERLISTING_BEGIN = "QUESTIONANSWERLISTING_BEGIN"
// export const QUESTIONANSWERLISTING_SUCCESS = "QUESTIONANSWERLISTING_SUCCESS"
// export const QUESTIONANSWERLISTING_FAILURE = "QUESTIONANSWERLISTING_FAILURE"

export const ADD_EDIT_QA_BEGIN = 'ADD_EDIT_QA_BEGIN'
export const ADD_EDIT_QA_FAILURE = 'ADD_EDIT_QA_FAILURE'

export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS'
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'

export const EDIT_ANSWER_SUCCESS = 'EDIT_ANSWER_SUCCESS'
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS'

export const LISTING_QA_BEGIN = 'LISTING_QA_BEGIN'
export const LISTING_QA_SUCCESS = 'LISTING_QA_SUCCESS'
export const LISTING_QA_FAILURE = 'LISTING_QA_FAILURE'

export const AUTH_ERROR_RESET = 'AUTH_ERROR_RESET'
export const THOUGHT_ERROR_RESET = 'THOUGHT_ERROR_RESET'
export const DASHBOARD_ERROR_RESET = 'DASHBOARD_ERROR_RESET'
export const ACTIONITEM_ERROR_RESET = 'ACTIONITEM_ERROR_RESET'
export const QUESTIONANSWER_ERROR_RESET = 'QUESTIONANSWER_ERROR_RESET'

export const QUESTION_DELETE_BEGIN = 'QUESTION_DELETE_BEGIN'
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_DELETE_FAILURE = 'QUESTION_DELETE_FAILURE'

export const ANSWER_DELETE_BEGIN = 'ANSWER_DELETE_BEGIN'
export const ANSWER_DELETE_SUCCESS = 'ANSWER_DELETE_SUCCESS'
export const ANSWER_DELETE_FAILURE = 'ANSWER_DELETE_FAILURE'

export const LOGOUT = 'LOGOUT'

export const JOURNAL_ADDEDIT_BEGIN = 'JOURNAL_ADDEDIT_BEGIN'
export const JOURNAL_ADDEDIT_SUCCESS = 'JOURNAL_ADDEDIT_SUCCESS'
export const JOURNAL_ADDEDIT_FAILURE = 'JOURNAL_ADDEDIT_FAILURE'

export const JOURNALS_LIST_BEGIN = 'JOURNALS_LIST_BEGIN'
export const JOURNALS_LIST_SUCCESS = 'JOURNALS_LIST_SUCCESS'
export const JOURNALS_LIST_FAILURE = 'JOURNALS_LIST_FAILURE'

export const JOURNAL_DELETE_BEGIN = 'JOURNAL_DELETE_BEGIN'
export const JOURNAL_DELETE_SUCCESS = 'JOURNAL_DELETE_SUCCESS'
export const JOURNAL_DELETE_FAILURE = 'JOURNAL_DELETE_FAILURE'

export const JOURNAL_VIEW_BEGIN = 'JOURNAL_VIEW_BEGIN'
export const JOURNAL_VIEW_SUCCESS = 'JOURNAL_VIEW_SUCCESS'
export const JOURNAL_VIEW_FAILURE = 'JOURNAL_VIEW_FAILURE'
