export const ADMIN_LOGIN_BEGIN = "USER_LOGIN_BEGIN"
export const ADMIN_LOGIN_FAILURE = "USER_LOGIN_FAILURE"
export const ADMIN_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"

export const FORGETPASSWORD_BEGIN = "FORGETPASSWORD_BEGIN"
export const FORGETPASSWORD_SUCCESS ="FORGETPASSWORD_SUCCESS"
export const FORGETPASSWORD_FAILURE ="FORGETPASSWORD_FAILURE"

export const RESETPASSWORD_BEGIN ="RESETPASSWORD_BEGIN"
export const RESETPASSWORD_SUCCESS ="RESETPASSWORD_SUCCESS"
export const RESETPASSWORD_FAILURE ="RESETPASSWORD_FAILURE"

export const EDITPROFILE = "EDITPROFILE"
export const VIEWPROFILE = "VIEWPROFILE"

export const DASHBOARDSTATUS_BEGIN="DASHBOARDSTATUS_BEGIN"
export const DASHBOARDSTATUS_SUCCESS="DASHBOARDSTATUS_SUCCESS"
export const DASHBOARDSTATUS_FAILURE="DASHBOARDSTATUS_FAILURE"

export const USERLISTING_BEGIN ="USERLISTING_BEGIN"
export const USERLISTING_SUCCESS ="USERLISTING_SUCCESS"
export const USERLISTING_FAILURE ="USERLISTING_FAILURE"

export const USERADDEDIT_BEGIN ="USERADDEDIT_BEGIN"
export const USERADDEDIT_SUCCESS ="USERADDEDIT_SUCCESS"
export const USERADDEDIT_FAILURE ="USERADDEDIT_FAILURE"

export const USERDELETE_BEGIN ="USERDELETE_BEGIN"
export const USERDELETE_SUCCESS ="USERDELETE_SUCCESS"
export const USERDELETE_FAILURE ="USERDELETE_FAILURE"

export const USERVIEW_BEGIN ="USERVIEW_BEGIN"
export const USERVIEW_SUCCESS ="USERVIEW_SUCCESS"
export const USERVIEW_FAILURE ="USERVIEW_FAILURE"

export const THOUGHTLISTING_BEGIN ="THOUGHTLIST_BEGIN"
export const THOUGHTLISTING_SUCCESS = "THOUGHTSLIST_SUCCESS"
export const THOUGHTLISTING_FAILURE ="THOUGHTLIST_FAILURE"

export const THOUGHTADDEDIT_BEGIN ="THOUGHTADDEDIT_BEGIN"
export const THOUGHTADDEDIT_SUCCESS ="THOUGHTADDEDIT_SUCCESS"
export const THOUGHTADDEDIT_FAILURE ="THOUGHTADDEDIT_FAILURE"

export const THOUGHTDELETE_BEGIN ="THOUGHTDELETE_BEGIN"
export const THOUGHTDELETE_SUCCESS = "THOUGHTDELETE_SUCCESS"
export const THOUGHTDELETE_FAILURE ="THOUGHTDELETE_FAILURE"

export const THOUGHTVIEW_BEGIN ="THOUGHTVIEW_BEGIN"
export const THOUGHTVIEW_SUCCESS = "THOUGHTVIEW_SUCCESS"
export const THOUGHTVIEW_FAILURE ="THOUGHTVIEW_FAILURE"

export const AUTH_ERROR_RESET = "AUTH_ERROR_RESET"
export const THOUGHT_ERROR_RESET = "THOUGHT_ERROR_RESET"

export const LOGOUT = "LOGOUT"